[project]
name = "base6-techo"
version = "0.1.0"
description = "Printable notebook desktop application"
readme = "README.md"
authors = [
    { name = "guozr", email = "guozr1997@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pytauri == 0.8.*",
    "Babel>=2.17.0",
    "astral>=3.2",
]

[project.entry-points.pytauri]
ext_mod = "ext_mod"

[build-system]
requires = ["setuptools >= 80", "setuptools-scm >= 8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["api", "app", "imposition", "latex", "layout", "models", "pages", "__main__"]

[tool.setuptools.packages]
find = { where = ["src-python"] }
