import { makePattern } from "../defaults";
import type { PatternKind, PipelineNode, SectionConfig } from "../types";
import { CityField } from "./CityField";
import { Group, NumberField, OptionalNumberField, OptionalTextField, SelectField, TextField, Toggle } from "./Fields";

type Props = { node: PipelineNode; update: (patch: Partial<PipelineNode["data"]>) => void; remove: () => void };
const PAPER_SIZES: Record<string, [number, number]> = {
  a5: [148, 210], a6: [105, 148], b5: [176, 250], b6: [125, 176],
};

export function Inspector({ node, update, remove }: Props) {
  const data = node.data;
  const updateSection = (patch: Partial<SectionConfig>) => update({ section: { ...data.section!, ...patch } });
  const updatePage = (patch: Partial<SectionConfig["page"]>) => updateSection({ page: { ...data.section!.page, ...patch } });
  const updateDocument = (patch: Partial<SectionConfig["document"]>) => updateSection({ document: { ...data.section!.document, ...patch } });
  const updatePattern = (patch: Record<string, unknown>) => updateSection({ pattern: { ...data.section!.pattern, ...patch } as SectionConfig["pattern"] });

  return <aside className="inspector">
    <header><div><span>Selected step</span><h2>{data.label}</h2></div><button className="quiet-button" onClick={remove}>Delete</button></header>
    <TextField label="Step name" value={data.label} onChange={(label) => update({ label })} />
    {data.kind === "section" ? <SectionInspector section={data.section!} updatePage={updatePage} updateDocument={updateDocument} updatePattern={updatePattern} replacePattern={(kind) => updateSection({ pattern: makePattern(kind) })} /> : null}
    {data.kind === "pages" ? <Group title="Blank pages" open><NumberField label="Before document" value={data.pages!.leading} min={0} step={1} onChange={(leading) => update({ pages: { ...data.pages!, leading } })} /><NumberField label="After document" value={data.pages!.trailing} min={0} step={1} onChange={(trailing) => update({ pages: { ...data.pages!, trailing } })} /></Group> : null}
    {data.kind === "bind" ? <Group title="Binding" open><SelectField label="Mode" value={data.bind!.mode ?? "none"} onChange={(mode) => update({ bind: { ...data.bind!, mode: mode === "none" ? null : mode as "booklet" | "thread" } })}><option value="booklet">Booklet</option><option value="thread">Thread / signatures</option><option value="none">No imposition</option></SelectField><NumberField label="Sheets per group" value={data.bind!.sheets_per_group} min={1} step={1} onChange={(sheets_per_group) => update({ bind: { ...data.bind!, sheets_per_group } })} /></Group> : null}
  </aside>;
}

function SectionInspector({ section, updatePage, updateDocument, updatePattern, replacePattern }: {
  section: SectionConfig;
  updatePage: (patch: Partial<SectionConfig["page"]>) => void;
  updateDocument: (patch: Partial<SectionConfig["document"]>) => void;
  updatePattern: (patch: Record<string, unknown>) => void;
  replacePattern: (kind: PatternKind) => void;
}) {
  const { page, document, pattern } = section;
  const paperSize = Object.entries(PAPER_SIZES).find(([, size]) => size[0] === page.width && size[1] === page.height)?.[0] ?? "custom";
  return <>
    <Group title="Section" open><SelectField label="Pattern" value={pattern.kind} onChange={(value) => replacePattern(value as PatternKind)}><option value="basic">Basic grid</option><option value="midori">Midori</option><option value="timeline">Timeline</option></SelectField><NumberField label="Page count" value={document.page_count} min={1} max={500} step={1} onChange={(page_count) => updateDocument({ page_count })} /><Toggle label="Participate in header" checked={document.show_header} onChange={(show_header) => updateDocument({ show_header })} /><Toggle label="Participate in footer numbering" checked={document.show_page_number} onChange={(show_page_number) => updateDocument({ show_page_number })} /></Group>
    <Group title="Paper geometry"><SelectField label="Preset" value={paperSize} onChange={(value) => { const size = PAPER_SIZES[value]; if (size) updatePage({ width: size[0], height: size[1] }); }}><option value="a5">A5 · 148 × 210</option><option value="a6">A6 · 105 × 148</option><option value="b5">ISO B5 · 176 × 250</option><option value="b6">ISO B6 · 125 × 176</option><option value="custom">Custom</option></SelectField><div /><NumberField label="Width (mm)" value={page.width} onChange={(width) => updatePage({ width })} /><NumberField label="Height (mm)" value={page.height} onChange={(height) => updatePage({ height })} /><NumberField label="Header space (mm)" value={page.header} min={0} onChange={(header) => updatePage({ header })} /><NumberField label="Footer space (mm)" value={page.footer} min={0} onChange={(footer) => updatePage({ footer })} /><NumberField label="Binding edge (mm)" value={page.binding} min={0} onChange={(binding) => updatePage({ binding })} /><NumberField label="Outer edge (mm)" value={page.non_binding} min={0} onChange={(non_binding) => updatePage({ non_binding })} /></Group>
    <Group title="Header date"><TextField label="Date" type="date" value={document.header_date ?? ""} onChange={(header_date) => updateDocument({ header_date: header_date || null })} /><TextField label="Date format" value={document.header_date_format} onChange={(header_date_format) => updateDocument({ header_date_format })} /><TextField label="Locale" value={document.header_date_locale} onChange={(header_date_locale) => updateDocument({ header_date_locale })} /><SelectField label="Pages" value={document.header_parity} onChange={(header_parity) => updateDocument({ header_parity: header_parity as typeof document.header_parity })}><option value="both">All</option><option value="odd">Odd</option><option value="even">Even</option></SelectField><SelectField label="Position" value={document.header_date_position} onChange={(header_date_position) => updateDocument({ header_date_position: header_date_position as typeof document.header_date_position })}><option value="center">Center</option><option value="binding">Binding edge</option><option value="outer">Outer edge</option></SelectField><NumberField label="Size (pt)" value={document.header_date_size} onChange={(header_date_size) => updateDocument({ header_date_size })} /><OptionalTextField label="Font" value={document.header_date_font} onChange={(header_date_font) => updateDocument({ header_date_font })} placeholder="Defaults to page font" /></Group>
    <Group title="Page number & spine"><TextField label="Page number font" value={document.page_number_font} onChange={(page_number_font) => updateDocument({ page_number_font })} /><OptionalTextField label="Spine line 1" value={document.binding_text} onChange={(binding_text) => updateDocument({ binding_text })} /><OptionalTextField label="Spine line 2" value={document.binding_text_2} onChange={(binding_text_2) => updateDocument({ binding_text_2 })} /><NumberField label="Line 1 size" value={document.binding_text_size} onChange={(binding_text_size) => updateDocument({ binding_text_size })} /><NumberField label="Line 2 size" value={document.binding_text_2_size} onChange={(binding_text_2_size) => updateDocument({ binding_text_2_size })} /><NumberField label="Line spacing" value={document.binding_text_spacing} min={0} onChange={(binding_text_spacing) => updateDocument({ binding_text_spacing })} /><TextField label="Spine font" value={document.binding_text_font} onChange={(binding_text_font) => updateDocument({ binding_text_font })} /></Group>
    <PatternInspector pattern={pattern} update={updatePattern} />
  </>;
}

function PatternInspector({ pattern, update }: { pattern: SectionConfig["pattern"]; update: (patch: Record<string, unknown>) => void }) {
  if (pattern.kind === "midori") return <><Group title="Midori pattern" open><NumberField label="Spacing" value={pattern.spacing} onChange={(spacing) => update({ spacing })} /><NumberField label="Gap" value={pattern.gap} onChange={(gap) => update({ gap })} /><NumberField label="Edge extension" value={pattern.edge_extension} onChange={(edge_extension) => update({ edge_extension })} /><NumberField label="Dot frequency" value={pattern.dot_frequency} min={1} step={1} onChange={(dot_frequency) => update({ dot_frequency })} /><NumberField label="Dot radius" value={pattern.dot_radius} onChange={(dot_radius) => update({ dot_radius })} /><NumberField label="Line width" value={pattern.line_width} onChange={(line_width) => update({ line_width })} /><TextField label="Line color" value={pattern.line_color} onChange={(line_color) => update({ line_color })} /><TextField label="Dot color" value={pattern.dot_color} onChange={(dot_color) => update({ dot_color })} /></Group><Group title="Midori extensions"><Toggle label="Header" checked={pattern.header} onChange={(header) => update({ header })} /><Toggle label="Footer" checked={pattern.footer} onChange={(footer) => update({ footer })} /><Toggle label="Binding edge" checked={pattern.inner} onChange={(inner) => update({ inner })} /><Toggle label="Outer edge" checked={pattern.outer} onChange={(outer) => update({ outer })} /></Group></>;
  if (pattern.kind === "timeline") return <Group title="Timeline pattern" open><NumberField label="Start hour" value={pattern.start} min={0} max={98} step={1} onChange={(start) => update({ start })} /><NumberField label="End hour" value={pattern.end} min={1} max={99} step={1} onChange={(end) => update({ end })} /><SelectField label="Spread" value={String(pattern.pages)} onChange={(pages) => update({ pages: Number(pages) })}><option value="1">Single page</option><option value="2">Two-page spread</option></SelectField><Toggle label="Swap left / right" checked={pattern.swap} onChange={(swap) => update({ swap })} /><NumberField label="Label size" value={pattern.label_size} onChange={(label_size) => update({ label_size })} /><NumberField label="Line width" value={pattern.line_width} onChange={(line_width) => update({ line_width })} /><TextField label="Default color" value={pattern.line_color} onChange={(line_color) => update({ line_color })} /><TextField label="Daylight color" value={pattern.daylight_color} onChange={(daylight_color) => update({ daylight_color })} /><TextField label="Night color" value={pattern.night_color} onChange={(night_color) => update({ night_color })} /><div className="wide"><CityField value={pattern.city_name} onChange={(city, city_name) => update({ city_name: city_name || null, latitude: city?.latitude ?? null, longitude: city?.longitude ?? null, timezone: city?.timezone ?? null })} /></div></Group>;
  return <><Group title="Basic pattern" open><NumberField label="Spacing" value={pattern.spacing} onChange={(spacing) => update({ spacing })} /><NumberField label="Line width" value={pattern.line_width} onChange={(line_width) => update({ line_width })} /><TextField label="Line color" value={pattern.line_color} onChange={(line_color) => update({ line_color })} /><Toggle label="Horizontal lines" checked={pattern.draw_hlines} onChange={(draw_hlines) => update({ draw_hlines })} /><Toggle label="Vertical lines" checked={pattern.draw_vlines} onChange={(draw_vlines) => update({ draw_vlines })} /><Toggle label="Dots" checked={pattern.draw_dots} onChange={(draw_dots) => update({ draw_dots })} /><OptionalNumberField label="Dot spacing" value={pattern.dot_spacing} onChange={(dot_spacing) => update({ dot_spacing })} /><NumberField label="Dot radius" value={pattern.dot_radius} onChange={(dot_radius) => update({ dot_radius })} /><OptionalNumberField label="Vertical spacing" value={pattern.vline_spacing} onChange={(vline_spacing) => update({ vline_spacing })} /><OptionalNumberField label="Margin line x" value={pattern.margin_x} onChange={(margin_x) => update({ margin_x })} /><OptionalTextField label="Margin color" value={pattern.margin_color} onChange={(margin_color) => update({ margin_color })} /></Group><Group title="Edge accents"><OptionalTextField label="Horizontal edge color" value={pattern.hline_edge_color} onChange={(hline_edge_color) => update({ hline_edge_color })} /><OptionalNumberField label="Horizontal edge width" value={pattern.hline_edge_width} onChange={(hline_edge_width) => update({ hline_edge_width })} /><OptionalTextField label="Vertical edge color" value={pattern.vline_edge_color} onChange={(vline_edge_color) => update({ vline_edge_color })} /><OptionalNumberField label="Vertical edge width" value={pattern.vline_edge_width} onChange={(vline_edge_width) => update({ vline_edge_width })} /><OptionalTextField label="Center dot color" value={pattern.dot_center_color} onChange={(dot_center_color) => update({ dot_center_color })} /></Group><RegionGroup title="Horizontal line regions" values={[pattern.hline_header, pattern.hline_footer, pattern.hline_inner, pattern.hline_outer]} update={(key, value) => update({ [`hline_${key}`]: value })} /><RegionGroup title="Vertical line regions" values={[pattern.vline_header, pattern.vline_footer, pattern.vline_inner, pattern.vline_outer]} update={(key, value) => update({ [`vline_${key}`]: value })} /><RegionGroup title="Dot regions" values={[pattern.dot_header, pattern.dot_footer, pattern.dot_inner, pattern.dot_outer]} update={(key, value) => update({ [`dot_${key}`]: value })} /></>;
}

function RegionGroup({ title, values, update }: { title: string; values: boolean[]; update: (key: string, value: boolean) => void }) {
  return <Group title={title}>{["header", "footer", "inner", "outer"].map((key, index) => <Toggle key={key} label={key === "inner" ? "Binding edge" : key === "outer" ? "Outer edge" : key[0].toUpperCase() + key.slice(1)} checked={values[index]} onChange={(value) => update(key, value)} />)}</Group>;
}
