[project]
name = "base6-techo"
version = "0.1.0"
description = "base6-techo 打印笔记本生成 SDK（调用 techo-pipeline CLI）"
readme = "README.md"
authors = [
    { name = "guozr", email = "guozr1997@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.13.5",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
