export type Output = string;
/**
 * @minItems 1
 */
export type Sections = [RenderSectionRequest, ...RenderSectionRequest[]];
export type Width = number;
export type Height = number;
export type Header = number;
export type Footer = number;
export type Binding = number;
export type NonBinding = number;
export type PageCount = number;
export type ShowHeader = boolean;
export type BindingText = string | null;
export type BindingText2 = string | null;
export type BindingTextSize = number;
export type BindingText2Size = number;
export type BindingTextSpacing = number;
export type BindingTextEdge = number | null;
export type BindingTextFont = string;
export type BindingTextColor = string;
export type HeaderDate = string | null;
export type HeaderDateEnd = string | null;
export type HeaderDateFormat = string;
export type HeaderDateLocale = string;
export type HeaderParity = "odd" | "even" | "both";
export type HeaderDateSize = number;
export type HeaderDateFont = string | null;
export type HeaderDatePosition = "center" | "binding" | "outer";
export type HeaderText = string | null;
export type HeaderText2 = string | null;
export type HeaderTextSize = number;
export type HeaderText2Size = number;
export type HeaderTextSpacing = number;
export type HeaderTextColor = string;
export type NonBindingText = string | null;
export type NonBindingText2 = string | null;
export type NonBindingTextSize = number;
export type NonBindingText2Size = number;
export type NonBindingTextSpacing = number;
export type NonBindingTextEdge = number | null;
export type NonBindingTextColor = string;
export type FooterText = string | null;
export type FooterText2 = string | null;
export type FooterTextSize = number;
export type FooterText2Size = number;
export type FooterTextSpacing = number;
export type FooterTextColor = string;
export type Pattern = BasicPatternRequest | MidoriPatternRequest | TimelinePatternRequest;
export type Kind = "basic";
export type Spacing = number;
export type LineWidth = number;
export type LineColor = string;
export type LineStyle = "solid" | "dashed" | "dotted" | "dash-dot" | "double-solid";
export type DrawHlines = boolean;
export type DrawVlines = boolean;
export type DrawDots = boolean;
export type HlineTopColor = string;
export type HlineTopWidth = number;
export type HlineTopStyle = LineStyle;
export type HlineBottomColor = string;
export type HlineBottomWidth = number;
export type HlineBottomStyle = LineStyle;
export type HlineCenterColor = string;
export type HlineCenterWidth = number;
export type HlineCenterStyle = LineStyle;
export type VlineLeftColor = string;
export type VlineLeftWidth = number;
export type VlineLeftStyle = LineStyle;
export type VlineRightColor = string;
export type VlineRightWidth = number;
export type VlineRightStyle = LineStyle;
export type VlineCenterColor = string;
export type VlineCenterWidth = number;
export type VlineCenterStyle = LineStyle;
export type DotCenterColor = string | null;
export type HlineHeader = boolean;
export type HlineFooter = boolean;
export type HlineInner = boolean;
export type HlineOuter = boolean;
export type VlineHeader = boolean;
export type VlineFooter = boolean;
export type VlineInner = boolean;
export type VlineOuter = boolean;
export type DotHeader = boolean;
export type DotFooter = boolean;
export type DotInner = boolean;
export type DotOuter = boolean;
export type DotSpacing = number | null;
export type DotRadius = number;
export type VlineSpacing = number | null;
export type VlineWidth = number;
export type VlineColor = string;
export type VlineStyle = LineStyle;
export type HlineTop = number;
export type HlineBottom = number;
export type HlineLeft = number;
export type HlineRight = number;
export type VlineTop = number;
export type VlineBottom = number;
export type VlineLeft = number;
export type VlineRight = number;
export type DotTop = number;
export type DotBottom = number;
export type DotLeft = number;
export type DotRight = number;
export type Kind1 = "midori";
export type Spacing1 = number;
export type Gap = number;
export type EdgeExtension = number;
export type DotFrequency = number;
export type DotRadius1 = number;
export type LineWidth1 = number;
export type LineColor1 = string;
export type DotColor = string;
export type Header1 = boolean;
export type Footer1 = boolean;
export type Inner = boolean;
export type Outer = boolean;
export type Kind2 = "timeline";
export type Start = number;
export type End = number;
export type Pages = 1 | 2;
export type LineColor2 = string;
export type LineWidth2 = number;
export type LabelSize = number;
export type CityName = string | null;
export type Latitude = number | null;
export type Longitude = number | null;
export type Timezone = string | null;
export type DaylightColor = string;
export type NightColor = string;
export type Mode = ("booklet" | "thread") | null;
export type SheetsPerGroup = number;

export interface RunPipelineRequest {
  output: Output;
  sections: Sections;
  bind?: BindRequest;
}
export interface RenderSectionRequest {
  page?: PageRequest;
  document?: DocumentRequest;
  pattern: Pattern;
}
export interface PageRequest {
  width?: Width;
  height?: Height;
  header?: Header;
  footer?: Footer;
  binding?: Binding;
  non_binding?: NonBinding;
}
export interface DocumentRequest {
  page_count?: PageCount;
  show_header?: ShowHeader;
  binding_text?: BindingText;
  binding_text_2?: BindingText2;
  binding_text_size?: BindingTextSize;
  binding_text_2_size?: BindingText2Size;
  binding_text_spacing?: BindingTextSpacing;
  binding_text_edge?: BindingTextEdge;
  binding_text_font?: BindingTextFont;
  binding_text_color?: BindingTextColor;
  header_date?: HeaderDate;
  header_date_end?: HeaderDateEnd;
  header_date_format?: HeaderDateFormat;
  header_date_locale?: HeaderDateLocale;
  header_parity?: HeaderParity;
  header_date_size?: HeaderDateSize;
  header_date_font?: HeaderDateFont;
  header_date_position?: HeaderDatePosition;
  header_text?: HeaderText;
  header_text_2?: HeaderText2;
  header_text_size?: HeaderTextSize;
  header_text_2_size?: HeaderText2Size;
  header_text_spacing?: HeaderTextSpacing;
  header_text_color?: HeaderTextColor;
  non_binding_text?: NonBindingText;
  non_binding_text_2?: NonBindingText2;
  non_binding_text_size?: NonBindingTextSize;
  non_binding_text_2_size?: NonBindingText2Size;
  non_binding_text_spacing?: NonBindingTextSpacing;
  non_binding_text_edge?: NonBindingTextEdge;
  non_binding_text_color?: NonBindingTextColor;
  footer_text?: FooterText;
  footer_text_2?: FooterText2;
  footer_text_size?: FooterTextSize;
  footer_text_2_size?: FooterText2Size;
  footer_text_spacing?: FooterTextSpacing;
  footer_text_color?: FooterTextColor;
}
export interface BasicPatternRequest {
  kind?: Kind;
  spacing?: Spacing;
  line_width?: LineWidth;
  line_color?: LineColor;
  line_style?: LineStyle;
  draw_hlines?: DrawHlines;
  draw_vlines?: DrawVlines;
  draw_dots?: DrawDots;
  hline_top_color?: HlineTopColor;
  hline_top_width?: HlineTopWidth;
  hline_top_style?: HlineTopStyle;
  hline_bottom_color?: HlineBottomColor;
  hline_bottom_width?: HlineBottomWidth;
  hline_bottom_style?: HlineBottomStyle;
  hline_center_color?: HlineCenterColor;
  hline_center_width?: HlineCenterWidth;
  hline_center_style?: HlineCenterStyle;
  vline_left_color?: VlineLeftColor;
  vline_left_width?: VlineLeftWidth;
  vline_left_style?: VlineLeftStyle;
  vline_right_color?: VlineRightColor;
  vline_right_width?: VlineRightWidth;
  vline_right_style?: VlineRightStyle;
  vline_center_color?: VlineCenterColor;
  vline_center_width?: VlineCenterWidth;
  vline_center_style?: VlineCenterStyle;
  dot_center_color?: DotCenterColor;
  hline_header?: HlineHeader;
  hline_footer?: HlineFooter;
  hline_inner?: HlineInner;
  hline_outer?: HlineOuter;
  vline_header?: VlineHeader;
  vline_footer?: VlineFooter;
  vline_inner?: VlineInner;
  vline_outer?: VlineOuter;
  dot_header?: DotHeader;
  dot_footer?: DotFooter;
  dot_inner?: DotInner;
  dot_outer?: DotOuter;
  dot_spacing?: DotSpacing;
  dot_radius?: DotRadius;
  vline_spacing?: VlineSpacing;
  vline_width?: VlineWidth;
  vline_color?: VlineColor;
  vline_style?: VlineStyle;
  hline_top?: HlineTop;
  hline_bottom?: HlineBottom;
  hline_left?: HlineLeft;
  hline_right?: HlineRight;
  vline_top?: VlineTop;
  vline_bottom?: VlineBottom;
  vline_left?: VlineLeft;
  vline_right?: VlineRight;
  dot_top?: DotTop;
  dot_bottom?: DotBottom;
  dot_left?: DotLeft;
  dot_right?: DotRight;
}
export interface MidoriPatternRequest {
  kind?: Kind1;
  spacing?: Spacing1;
  gap?: Gap;
  edge_extension?: EdgeExtension;
  dot_frequency?: DotFrequency;
  dot_radius?: DotRadius1;
  line_width?: LineWidth1;
  line_color?: LineColor1;
  dot_color?: DotColor;
  header?: Header1;
  footer?: Footer1;
  inner?: Inner;
  outer?: Outer;
}
export interface TimelinePatternRequest {
  kind?: Kind2;
  start?: Start;
  end?: End;
  pages?: Pages;
  line_color?: LineColor2;
  line_width?: LineWidth2;
  label_size?: LabelSize;
  city_name?: CityName;
  latitude?: Latitude;
  longitude?: Longitude;
  timezone?: Timezone;
  daylight_color?: DaylightColor;
  night_color?: NightColor;
}
export interface BindRequest {
  mode?: Mode;
  sheets_per_group?: SheetsPerGroup;
}
